# 禁止一切指令执行
deny-any-command:
  enable: false
  # 是否同时禁止编辑 CB
  lock-cb: true
  # 解锁密码
  unlock-password: 123456
  # 允许的指令白名单
  white-list:
    - list
    - tps
    - skin

# 根据 TPS 调整配置
# 每 100tick 调整一次
tps-configure:
  enable: false
  # 限制比例(>= TPS: 各项参数控制比例)
  # 注意：请用 x 代替 .，例如 19.5 写为 19x5
  rates:
    19x5: 100
    19: 90
    18: 80
    17: 70
    16: 60
    15: 50
    14: 40
    13: 30
    12: 20
    11: 17
    10: 15
    9: 13
    8: 11
    7: 9
    6: 7
    5: 6
    4: 5
    3: 4
    2: 3
    1: 2
    0: 1
  # 内部用于控制的 TPS 最大单次回升量
  max-up: 0.8
